name: Build tree-sitter Python wheel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11']

    steps:
      - name: Checkout py-tree-sitter with submodules
        uses: actions/checkout@v4
        with:
          repository: tree-sitter/py-tree-sitter
          ref: v0.20.1  # 👈 Pin to specific version
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: pip install build

      - name: Build wheel
        run: python -m build --wheel

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: tree-sitter-${{ runner.os }}-py${{ matrix.python-version }}
          path: dist/*.whl
