name: Build tree-sitter wheel

on:
  workflow_dispatch:  # manual trigger

jobs:
  build-wheel:
    name: Build on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Checkout tree-sitter Python bindings
      uses: actions/checkout@v3
      with:
        repository: tree-sitter/py-tree-sitter
        ref: v0.20.1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools wheel

    - name: Build wheel
      run: python -m build --wheel

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v4
      with:
        name: tree_sitter-${{ matrix.os }}-py${{ matrix.python-version }}
        path: dist/*.whl
